version: '3'

services:

  app:
    build: 
      ./nodejs
    volumes: 
      - ./nodejs:/home/node/app
    ports:
      - "3000:3000"

  mysql:
    image: 
      mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco

    volumes:
      - ./mysql:/var/lib/mysql
  

    




